#!/bin/bash
# SCRIPT DE INSTALACIÓN - Sistema de Reseñas y Calificaciones

echo "========================================="
echo "SISTEMA DE RESEÑAS Y CALIFICACIONES"
echo "========================================="
echo ""
echo "📦 Tamaño Total: ~67KB de código nuevo"
echo "🔧 Archivos Nuevos: 7"
echo "✏️  Archivos Modificados: 6"
echo "🧪 Test Cases: 26"
echo "📚 Documentación: 22KB"
echo ""

echo "=== PASO 1: MIGRACIÓN DE BASE DE DATOS ==="
echo "Ejecute en el directorio backend:"
echo ""
echo "  cd backend"
echo "  npx prisma migrate dev --name add_review_model"
echo ""

echo "=== PASO 2: VERIFICAR COMPILACIÓN ==="
echo ""
echo "  npm run build"
echo ""

echo "=== PASO 3: EJECUTAR TESTS ==="
echo ""
echo "  npm run test -- review.service.test.ts"
echo ""

echo "=== PASO 4: INICIAR SERVIDOR ==="
echo ""
echo "  npm run dev"
echo ""

echo "=== ENDPOINTS DISPONIBLES ==="
echo ""
echo "Crear reseña:"
echo "  POST /api/reviews"
echo ""
echo "Obtener reseñas de barbero:"
echo "  GET /api/reviews/barber/{barberId}?page=1&limit=10"
echo ""
echo "Ver mis reseñas:"
echo "  GET /api/reviews/my-reviews"
echo ""
echo "Rating de barbero:"
echo "  GET /api/barbers/{barberId}/rating"
echo ""
echo "Reportar reseña:"
echo "  POST /api/reviews/{id}/report"
echo ""

echo "=== DOCUMENTACIÓN ==="
echo ""
echo "📖 Guía completa: backend/REVIEWS_SETUP.md"
echo "📋 Resumen implementación: backend/IMPLEMENTATION_SUMMARY_REVIEWS.md"
echo "✅ Verificación: REVIEW_SYSTEM_VERIFICATION.md"
echo ""

echo "=== CARACTERÍSTICAS PRINCIPALES ==="
echo ""
echo "✨ Reseñas verificadas (solo después de completar reserva)"
echo "⭐ Calificaciones 1-5 estrellas"
echo "💬 Comentarios hasta 1000 caracteres"
echo "📷 Hasta 5 imágenes por reseña"
echo "👍 Marcar útil/no útil"
echo "🚨 Reportar inapropiadas"
echo "👨‍💼 Admin puede eliminar reportadas"
echo "📊 Cálculo automático de ratings"
echo "📈 Distribución de calificaciones"
echo ""

echo "=== IMPORTANTE ==="
echo ""
echo "1. El schema.prisma ya incluye el modelo Review"
echo "2. Las rutas están registradas en server.ts"
echo "3. Los controladores están integrados"
echo "4. Las validaciones están completas"
echo "5. Los tests están listos para ejecutar"
echo ""

echo "========================================="
echo "✅ IMPLEMENTACIÓN COMPLETADA"
echo "========================================="
echo ""
echo "Para preguntas, consulte:"
echo "- REVIEWS_SETUP.md (guía técnica)"
echo "- IMPLEMENTATION_SUMMARY_REVIEWS.md (detalles)"
echo "- Documentación Swagger en /api/docs"
echo ""
