import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from '../hooks/useAuth';
export default function HomePage({ user, barbers, barbersLoading, getBarberRating }) {
    const { logout } = useAuth();
    const handleLogout = async () => {
        await logout();
    };
    return (_jsxs("div", { className: "min-h-screen bg-gradient-to-br from-dark-primary to-dark-secondary p-8", children: [_jsxs("header", { className: "mb-12 flex justify-between items-center", children: [_jsx("h1", { className: "text-5xl font-bebas text-accent", children: "Barber Booking" }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("span", { className: "text-white", children: ["Bienvenido, ", user?.user_metadata?.full_name || user?.email] }), _jsx("button", { onClick: handleLogout, className: "bg-accent text-dark-primary px-4 py-2 rounded font-bold hover:bg-opacity-80", children: "Cerrar Sesi\u00F3n" })] })] }), _jsxs("main", { children: [_jsx("h2", { className: "text-3xl font-bebas text-white mb-8", children: "Nuestros Barberos" }), barbersLoading ? (_jsx("div", { className: "text-center text-white text-xl", children: "Cargando barberos..." })) : barbers.length === 0 ? (_jsx("div", { className: "text-center text-white text-xl", children: "No hay barberos disponibles" })) : (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: barbers.map((barber) => (_jsxs("div", { className: "bg-dark-secondary rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-shadow", children: [barber.image_url && (_jsx("img", { src: barber.image_url, alt: barber.name, className: "w-full h-48 object-cover" })), _jsxs("div", { className: "p-6", children: [_jsx("h3", { className: "text-2xl font-bebas text-accent mb-2", children: barber.name }), _jsx("p", { className: "text-gray-400 text-sm mb-3", children: barber.specialty }), _jsx("p", { className: "text-white mb-3", children: barber.bio }), _jsxs("div", { className: "flex justify-between items-center mb-4", children: [_jsxs("span", { className: "text-accent font-bold", children: ["\u2B50 ", getBarberRating(barber.id), "/5"] }), _jsx("span", { className: "text-gray-400", children: barber.phone })] }), _jsx("button", { className: "w-full bg-accent text-dark-primary font-bold py-2 rounded hover:bg-opacity-80", children: "Reservar" })] })] }, barber.id))) }))] })] }));
}
